version: "3.7"
services:
  
  banco:
    env_file: .env
    build:
      context: .
      args: 
        TAG: alpine
    volumes: 
      - pg_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

volumes: 
  pg_data:
